### ISSUE TITLE
BAT framework: Could not find or load main class org.mule.weave.v2.runtime.utils.WeaveRunner

### ISSUE THREAD

**Issue by YannickG1** [mulesoft-labs/data-weave-intellij-plugin#35]
Hi,

I can't seem to able to get the BAT working using this plugin. I followed the official guide (https://docs.mulesoft.com/api-functional-monitoring/bat-intellij-idea) which led me to installing this plugin, but when I try to run one of the tests, it always exits with "Could not find or load main class org.mule.weave.v2.runtime.utils.WeaveRunner". I tried installing the Mule 4 plugin as well, downloading the latest mule-ee runtime and pointing the mule framework config to this folder. As last step I did "Add framework support" on my BAT project and all mule jars appeared in the "External libraries", but still it is throwing this error. What am I doing wrong ? 

Thanks in advance.

![image](https://user-images.githubusercontent.com/3669955/56746339-4d2e5b00-677c-11e9-9390-2a824b70f3af.png)

**Comment by nbattiato** [comment]
Hi,

Try doing this:

1 - Close intelli.
2 - Remove intellij files & folders from your test project (.idea folder and.iml file, in you case is bat.iml).
4 - Re-configure intellij file executing `bat idea` command on the project root.
5 - Open the project on intellij again, set up JDK on the project.
6 - Open the test you want to execute, right clic on the editor - > Run -> Bat Test NameOfYourTest

Let me know if it helps!

**Comment by YannickG1** [comment]
Hi,

Ok it works now... Still wondering why it didn't work in the first place. Only thing I did different this time I think is not using the built-in terminal of IntelliJ but an external one, must be something that IntelliJ does behind the scenes with its files.

Thanks a lot !

**Comment by nbattiato** [comment]
No problem, you have to run the `bat idea` command before open it with intellij. i think that was the problem.
