### ISSUE TITLE
Plugin repository doesn't work in PhpStorm 2019.3

### ISSUE THREAD

**Issue by achekulaev** [mulesoft-labs/data-weave-intellij-plugin#43]
Adding `https://plugins.jetbrains.com/plugins/Develop/10362` as plugins repository url gives `No plugins found. Please check log file for possible errors.`

<img width="977" alt="Screen Shot 2019-12-10 at 8 37 51 AM" src="https://user-images.githubusercontent.com/402007/70534148-6c6dd300-1b28-11ea-846c-f09c403b03ba.png">

**Comment by GauthierPLM** [comment]
The plugins are supposed to support only IntelliJ IDEA and Android Studio, as they require the Java module, not included in PHPStorm.

Thus, there is indeed no plugin available and I guess the repository cannot be added.
