### ISSUE TITLE
Mule SDK download - BASE_URL Access Denied (intellij-mule-runtime.s3.amazonaws.com/mule4)

### ISSUE THREAD

**Issue by mcleandaniel** [mulesoft-labs/data-weave-intellij-plugin#47]
When downloading a Mule SDK via the Mule4 plugin popup, an error is seen in the Intellij log (attached).

[mule4-plugin.log](https://github.com/mulesoft-labs/data-weave-intellij-plugin/files/5011335/mule4-plugin.log)

org.mule.tooling.runtime.sdk.ui.MuleSdkSelectionDialog.downloadVersionWithProgress(MuleSdkSelectionDialog.java:140)

Looking in the data-weave-intellij-plugin/mule-esb-plugin/src/main/java/org/mule/tooling/runtime/sdk/Mule4Url.java class, we can see that BASE_URL is set to "http://intellij-mule-runtime.s3.amazonaws.com/mule4".

Attempting to access to BASE_URL is Denied (<Message>Access Denied</Message>) for both the folder and index.xml

**Comment by machaval** [comment]
Hi @mcleandaniel  Saddly the mule plugin is no longer developed so no bugs are going to get fixed. Sorry for the bad news
