### ISSUE TITLE
Option to increase the memory allocated to the Dataweave runtime

### ISSUE THREAD

**Issue by benoitde** [mulesoft-labs/data-weave-intellij-plugin#50]
Hi,

Since I found this tool, I have been using extensively to develop the most complex Dataweave of my projects. Some of the payloads I have to deal with are quite large, and the tool becomes almost non-responding in these cases, the fan and the CPU of my computer are running like crazy when this happens.

I should note, that the Docker dw-playground can deal with the same dataweave/payloads relatively easily. In Studio, I increase the memory allocated to the Mule engine by modifying the _wrapper.conf.template_ file.

Is there a way to increase the memory allocate to the Dataweave runtime used by the plugin?

Thanks

**Comment by machaval** [comment]
Hi @benoitde, currently that configuration is not supported. But we can try to add it looks like a valid use case

**Comment by machaval** [comment]
I've merge this in the latest version
